### ISSUE TITLE
Milestone 2 Code Feedback

### ISSUE THREAD

**Issue by ahofmann4** [UBC-MDS/dsci522-group16#35]
- code is very well written in script files
- a results folder with different files would be beneficial to save outputs from the scripts
- no data files saved that could be read into the report

The main errors I ran into where filepath name problems. I wasn't able to track all of them since there were so many. See below for a review of the errors I encountered running your code with the commands you provided in your ReadME. I am confident that you will be able to fix these errors, and don't be discouraged by your mark. I can see that overall you have a good understanding of the material and processes, these errors are just overshadowing all the good work you did do!

-----------------
Setting environment from yml gives this error:
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound: 
  - warnings

remove warnings from .yml file

-------------------

Python download_data.py --url='https://archive.ics.uci.edu/ml/machine-learning-databases/00451/dataR2.csv' --out_file='C:/data/raw/data.csv'
Python: can't open file 'download_data.py': [Errno 2] No such file or directory

src/download_data.py is what is needed here
--------------------
Python split_train_test.py --in_train_file='C:/dataR2.csv' --train_out='C:/data/raw/train.csv' --test_out='C:/data/raw/test.csv'
Python: can't open file 'split_train_test.py': [Errno 2] No such file or directory

src needed again in file path
------------------------------
Python src/split_train_test.py --in_train_file='C:/dataR2.csv' --train_out='C:/data/raw/train.csv' --test_out='C:/data/raw/test.csv'
Traceback (most recent call last):
  File "src/split_train_test.py", line 24, in <module>
    raw_data = pd.read_csv(in_train_file)
  File "/opt/miniconda3/envs/group16/lib/python3.8/site-packages/pandas/io/parsers.py", line 688, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/opt/miniconda3/envs/group16/lib/python3.8/site-packages/pandas/io/parsers.py", line 454, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/opt/miniconda3/envs/group16/lib/python3.8/site-packages/pandas/io/parsers.py", line 948, in __init__
    self._make_engine(self.engine)
  File "/opt/miniconda3/envs/group16/lib/python3.8/site-packages/pandas/io/parsers.py", line 1180, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/opt/miniconda3/envs/group16/lib/python3.8/site-packages/pandas/io/parsers.py", line 2010, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'C:/dataR2.csv'

appears to be a lot of file path errors, not enough of the file path names are designated it seems
------------------------------
Python generate_figs.py  --figure_1='/figures/class_imbalance_check.png'  --figure_2='./figures/pairplot.png'
Python: can't open file 'generate_figs.py': [Errno 2] No such file or directory

again file path name problems, src/generate_figs.py needed to make this call work

**Comment by IfyAnene7** [comment]
Thank you so much again @ahofmann4 for the feedback!

We have been able to sort most of these out, I think the main problem was with the YAML file, and removing warnings and making a few edits sorted everything out.
